# Contains global cross-service properties
server:
  #Does not need to be changed.
  port: ${SERVER_PORT:8080}
  undertow:
    buffer-size: 8192
    max-regions: 10
    io-threads: 4
    worker-threads: 32
    direct-buffers: true

---

spring:
  profile: minikube

jdbc.url: jdbc:mysql://tds-mysql-db-deployment.cugsexobhx8t.us-west-2.rds.amazonaws.com:3306

spring:
  datasource:
    # DB Connection information.
    username: "tds-read-only"
    password: '{cipher}496d3916a38db6c0942c2a448e836335d7866c89bc3115558343137f65f56979'
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: 'com.mysql.jdbc.Driver'
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: "SELECT 1"
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  rabbitmq:
    # Username and password for rabbitmq
    username: "services"
    password: '{cipher}0021e4cf506604e24480ecc57dde8b15948e9e69b0ea04dc6d2d21971765df88'

tds:
  cache:
    enabled: true
    implementation: redis

flyway:
  enabled: false

logging:
  level:
    root: WARN

spring-config-url: http://localhost:8888
logstash-destination: logstash-dev.sbtds.org:4560

---

spring:
  profile: local-development
