# Contains properties for the tds-session-service.
# Properties not defined in a profile are global to all profiles.  Profiles sections can override the global values.
spring:
  datasource:
    # DB Connection information
    url: jdbc:mysql://tds-mysql-db-deployment.cugsexobhx8t.us-west-2.rds.amazonaws.com:3306/session

session-service:
  examUrl: http://tds-exam-service/

