# Contains properties for the tds-student-service.
spring:
  datasource:
    # DB Connection information
    url: jdbc:mysql://tds-mysql-db-deployment.cugsexobhx8t.us-west-2.rds.amazonaws.com:3306/session
