# Contains properties for the tds-config-service.
# Properties not defined in a profile are global to all profiles.  Profiles sections can override the globabl values.
spring:
  profile: minikube
  datasource:
    # DB Connection information
    url: ${jdbc.host}/configs
