# Contains properties for the exam-service.
spring:
  profile: minikube
  ds_queries:
    # DB Connection Information
    jdbcUrl: ${sbac.jdbc.host}/exam
  ds_commands:
    # DB Connection Information
    jdbcUrl: ${sbac.jdbc.host}/exam

#Hosts defined in TDS_Build:docker-compose.yml
exam-service:
  session-url: http://tds-session-service
  student-url: http://tds-student-service
  assessment-url: http://tds-assessment-service
  config-url: http://tds-config-service

exam:
  # Specific scoring settings. Should not need to change
  scoring:
    engine:
      queueThreadCount: 1
      queueHiWaterMark: 500
      queueLowWaterMark: 400
      maxAttempts: 3
      sympyTimeoutMillis: 1000
      # If using Kubernetes deployment this should not need to be changed
      pythonScoringUrl: http://tds-equation-scoring-service/

---
# Local docker-compose profile
# Note that this requires a MySql database running on your localhost.
# Configure the following container environment variables for database access (in TDS_Build:docker-compose.yml)
# SBAC_JDBC_HOST=jdbc:mysql://192.168.0.139:3306 (Replace the host name with your computer's local network IP)
# SBAC_USER=username
# SBAC_PASSWORD=password
spring:
  profiles: local-docker
  ds_queries:
    jdbcUrl: ${sbac.jdbc.host}/exam
    username: ${sbac.jdbc.user}
    password: ${sbac.jdbc.password}
  ds_commands:
    jdbcUrl: ${sbac.jdbc.host}/exam
    username: ${sbac.jdbc.user}
    password: ${sbac.jdbc.password}
